#!/usr/bin/env bash
# build-dvisvgm-wasm.sh — compile dvisvgm (DVI -> SVG, with PGF/TikZ special
# support) to WebAssembly. Same recipe shape as build-tex-wasm.sh: the native
# configure of texk/dvisvgm supplies config.h, everything else is compiled
# with em++ from the vendored sources. FreeType and zlib come from Emscripten's
# ports; kpathsea objects are shared with tex.wasm; potrace, clipper, md5 and
# xxHash are the bundled copies. Ghostscript is not linked in: dvisvgm's
# dlopen of libgs is answered by src/c/gs-bridge.c, which forwards to a
# separate Ghostscript module when the host has loaded one (patches/dvisvgm/0002).
# WOFF output stays in. patches/dvisvgm/*.patch are applied to a copy of src/
# first.
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TL="$REPO/vendor/texlive-source"
NB="$REPO/vendor/native-build"
DVS="$TL/texk/dvisvgm/dvisvgm-src"
OUT="$REPO/build/dvisvgm"
TEXOUT="$REPO/build/tex"
DIST="$REPO/dist"
EMCC="${EMCC:-emcc}"; EMXX="${EMXX:-em++}"
JOBS="${JOBS:-8}"
# -Oz, as every release has been linked (0.1.0-0.3.0) and as the guide documents;
# the default here used to say -O2, which links 48 KB larger with readable import
# names, so a plain source build did not reproduce the released engine.
OPT="${DVISVGM_OPT:--Oz}"

[ -f "$NB/texk/dvisvgm/config.h" ] || { echo "error: configure texk/dvisvgm natively first (vendor/native-build/texk/dvisvgm/config.h)" >&2; exit 1; }
ls "$TEXOUT"/obj/kpathsea-*.o >/dev/null 2>&1 || { echo "error: run scripts/build-tex-wasm.sh first (kpathsea objects are shared)" >&2; exit 1; }
mkdir -p "$OUT/obj" "$OUT/include/ttf" "$DIST"
# src/ttf/NameTable.cpp includes "../version.hpp" relative to an include dir
cp "$NB/texk/dvisvgm/dvisvgm-src/src/version.hpp" "$OUT/include/version.hpp"

# ---- source patches: patches/dvisvgm/*.patch are applied to a copy of src/
# under $PS (the vendored tree is never modified), and everything in src/ is
# compiled from the copy under its usual object name. The whole of src/ is
# copied, not just the patched files, because its sources include their
# headers with quotes, which looks beside the including file first: a patched
# header has to sit next to every source that includes it. Nothing here tracks
# header dependencies, so a change to the set of patches, or to the flags
# below, rebuilds every object.
PS="$OUT/patched"; rm -rf "$PS"; mkdir -p "$PS"; cp -Rp "$DVS/src" "$PS/src"
for p in "$REPO"/patches/dvisvgm/*.patch; do
  [ -f "$p" ] || continue
  echo "==> applying $(basename "$p")"
  patch -s -p1 -d "$PS" < "$p"
done
# version.hpp is generated by the native configure inside the build tree
INC="-I$NB/texk/dvisvgm -I$OUT/include -I$OUT/include/ttf -I$PS/src -I$DVS/libs/variant/include -I$DVS/libs/boost -I$DVS/libs/md5 -I$DVS/libs/clipper -I$DVS/libs/xxHash -I$DVS/libs/woff2/include -I$DVS/libs/brotli/include -I$NB/libs/potrace/include -I$TEXOUT/include -I$TL/texk"
# WOFF output stays enabled: upstream's DISABLE_WOFF stub does not compile, and
# the bundled woff2/brotli are small. Ghostscript support is compiled in (no
# DISABLE_GS, no HAVE_LIBGS: the dlopen path, which gs-bridge.c answers).
DEFS="-DHAVE_CONFIG_H -DTEXLIVE_BUILD=1"
COMMON="$OPT -w -fwasm-exceptions -sWASM_LEGACY_EXCEPTIONS=1 -sUSE_FREETYPE=1 -sUSE_ZLIB=1"
CXXFLAGS="$COMMON -std=c++17"
CFLAGS="$COMMON"
STAMP=$( (cat /dev/null "$REPO"/patches/dvisvgm/*.patch 2>/dev/null; echo "$DEFS $COMMON") | shasum | cut -d' ' -f1 || true)
if [ "$(cat "$OUT/obj/.patches" 2>/dev/null)" != "$STAMP" ]; then
  rm -f "$OUT"/obj/*.o; echo "$STAMP" > "$OUT/obj/.patches"
fi

SRCS=()
for f in "$DVS"/src/*.cpp "$DVS"/src/fonts/*.cpp "$DVS"/src/optimizer/*.cpp "$DVS"/src/ttf/*.cpp; do
  case "$f" in */MiKTeXCom.cpp) continue;; esac   # Windows/MiKTeX only
  SRCS+=("$f")
done
SRCS+=("$DVS/libs/clipper/clipper.cpp" "$DVS/libs/md5/md5.c" "$DVS/libs/xxHash/xxhash.c")
for f in "$DVS"/libs/woff2/src/*.cc; do SRCS+=("$f"); done
while IFS= read -r f; do SRCS+=("$f"); done < <(find "$DVS/libs/brotli" -name '*.c' | sort)
for f in curve decompose potracelib trace; do SRCS+=("$TL/libs/potrace/potrace-src/src/$f.c"); done
SRCS+=("$REPO/src/c/gs-bridge.c")   # the "libgs" dvisvgm dlopen()s (patches/dvisvgm/0002)

echo "==> compiling ${#SRCS[@]} files ($OPT)"
OBJS=()
n=0
for src in "${SRCS[@]}"; do
  # object names derive from the whole path: Font.cpp and woff2's font.cc would
  # otherwise collide on a case-insensitive filesystem
  obj="$OUT/obj/$(echo "${src%.*}" | sed "s#^$TL/##; s#^texk/dvisvgm/dvisvgm-src/##; s#^$REPO/src/c/#mpw-#; s#[/.]#-#g").o"
  OBJS+=("$obj")
  case "$src" in "$DVS"/src/*) src="$PS/src/${src#"$DVS"/src/}";; esac   # the patched copy
  extra=""
  case "$src" in */potrace-src/*) extra="-I$NB/libs/potrace -I$TL/libs/potrace/potrace-src/src";; esac
  if [ ! -f "$obj" ] || [ "$src" -nt "$obj" ]; then
    case "$src" in
      *.cpp|*.cc) $EMXX $CXXFLAGS $DEFS $INC $extra -c -o "$obj" "$src" & ;;
      *.c)   $EMCC $CFLAGS $DEFS $INC $extra -c -o "$obj" "$src" & ;;
    esac
    n=$((n+1)); if [ $((n % JOBS)) = 0 ]; then wait; fi
  fi
done
wait

echo "==> linking dist/dvisvgm.mjs"
$EMXX $OPT -fwasm-exceptions -sWASM_LEGACY_EXCEPTIONS=1 -sUSE_FREETYPE=1 -sUSE_ZLIB=1 -o "$DIST/dvisvgm.mjs" "${OBJS[@]}" "$TEXOUT"/obj/kpathsea-*.o \
  -sMODULARIZE=1 -sEXPORT_ES6=1 -sEXPORT_NAME=createDvisvgm \
  -sENVIRONMENT=web,worker,node \
  -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=67108864 -sMAXIMUM_MEMORY=2147483648 \
  -sSTACK_SIZE=4194304 \
  -sFILESYSTEM=1 -sFORCE_FILESYSTEM=1 \
  -sINVOKE_RUN=0 -sEXIT_RUNTIME=1 \
  -sEXPORTED_FUNCTIONS=_main,_malloc,_free \
  -sEXPORTED_RUNTIME_METHODS=FS,callMain,ENV,NODEFS,MEMFS,stringToNewUTF8,UTF8ToString,HEAPU8 \
  -sINCOMING_MODULE_JS_API=arguments,thisProgram,preRun,postRun,print,printErr,locateFile,wasmBinary,noInitialRun,onRuntimeInitialized,instantiateWasm,onExit,quit \
  -sERROR_ON_UNDEFINED_SYMBOLS=1 \
  -lnodefs.js \
  --js-library "$REPO/src/c/gs-bridge.js" \
  -Wno-unused-command-line-argument
ls -l "$DIST/dvisvgm.mjs" "$DIST/dvisvgm.wasm"
