#!/usr/bin/env bash
# build-dvisvgm-wasm.sh — compile dvisvgm (DVI -> SVG, with PGF/TikZ special
# support) to WebAssembly. Same recipe shape as build-tex-wasm.sh: the native
# configure of texk/dvisvgm supplies config.h, everything else is compiled
# with em++ from the vendored sources. FreeType and zlib come from Emscripten's
# ports; kpathsea objects are shared with tex.wasm; potrace, clipper, md5 and
# xxHash are the bundled copies. Ghostscript (PostScript specials) and WOFF
# font output are compiled out.
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TL="$REPO/vendor/texlive-source"
NB="$REPO/vendor/native-build"
DVS="$TL/texk/dvisvgm/dvisvgm-src"
OUT="$REPO/build/dvisvgm"
TEXOUT="$REPO/build/tex"
DIST="$REPO/dist"
EMCC="${EMCC:-emcc}"; EMXX="${EMXX:-em++}"
JOBS="${JOBS:-8}"
OPT="${DVISVGM_OPT:--O2}"

[ -f "$NB/texk/dvisvgm/config.h" ] || { echo "error: configure texk/dvisvgm natively first (vendor/native-build/texk/dvisvgm/config.h)" >&2; exit 1; }
ls "$TEXOUT"/obj/kpathsea-*.o >/dev/null 2>&1 || { echo "error: run scripts/build-tex-wasm.sh first (kpathsea objects are shared)" >&2; exit 1; }
mkdir -p "$OUT/obj" "$OUT/include/ttf" "$DIST"
# src/ttf/NameTable.cpp includes "../version.hpp" relative to an include dir
cp "$NB/texk/dvisvgm/dvisvgm-src/src/version.hpp" "$OUT/include/version.hpp"

# version.hpp is generated by the native configure inside the build tree
INC="-I$NB/texk/dvisvgm -I$OUT/include -I$OUT/include/ttf -I$DVS/src -I$DVS/libs/variant/include -I$DVS/libs/boost -I$DVS/libs/md5 -I$DVS/libs/clipper -I$DVS/libs/xxHash -I$DVS/libs/woff2/include -I$DVS/libs/brotli/include -I$NB/libs/potrace/include -I$TEXOUT/include -I$TL/texk"
# WOFF output stays enabled: upstream's DISABLE_WOFF stub does not compile, and
# the bundled woff2/brotli are small. Ghostscript (PostScript specials) is out.
DEFS="-DHAVE_CONFIG_H -DDISABLE_GS -DTEXLIVE_BUILD=1"
COMMON="$OPT -w -fwasm-exceptions -sWASM_LEGACY_EXCEPTIONS=1 -sUSE_FREETYPE=1 -sUSE_ZLIB=1"
CXXFLAGS="$COMMON -std=c++17"
CFLAGS="$COMMON"

SRCS=()
for f in "$DVS"/src/*.cpp "$DVS"/src/fonts/*.cpp "$DVS"/src/optimizer/*.cpp "$DVS"/src/ttf/*.cpp; do
  case "$f" in */MiKTeXCom.cpp) continue;; esac   # Windows/MiKTeX only
  SRCS+=("$f")
done
SRCS+=("$DVS/libs/clipper/clipper.cpp" "$DVS/libs/md5/md5.c" "$DVS/libs/xxHash/xxhash.c")
for f in "$DVS"/libs/woff2/src/*.cc; do SRCS+=("$f"); done
while IFS= read -r f; do SRCS+=("$f"); done < <(find "$DVS/libs/brotli" -name '*.c' | sort)
for f in curve decompose potracelib trace; do SRCS+=("$TL/libs/potrace/potrace-src/src/$f.c"); done

echo "==> compiling ${#SRCS[@]} files ($OPT)"
OBJS=()
n=0
for src in "${SRCS[@]}"; do
  # object names derive from the whole path: Font.cpp and woff2's font.cc would
  # otherwise collide on a case-insensitive filesystem
  obj="$OUT/obj/$(echo "${src%.*}" | sed "s#^$TL/##; s#^texk/dvisvgm/dvisvgm-src/##; s#[/.]#-#g").o"
  OBJS+=("$obj")
  extra=""
  case "$src" in */potrace-src/*) extra="-I$NB/libs/potrace -I$TL/libs/potrace/potrace-src/src";; esac
  if [ ! -f "$obj" ] || [ "$src" -nt "$obj" ]; then
    case "$src" in
      *.cpp|*.cc) $EMXX $CXXFLAGS $DEFS $INC $extra -c -o "$obj" "$src" & ;;
      *.c)   $EMCC $CFLAGS $DEFS $INC $extra -c -o "$obj" "$src" & ;;
    esac
    n=$((n+1)); if [ $((n % JOBS)) = 0 ]; then wait; fi
  fi
done
wait

echo "==> linking dist/dvisvgm.mjs"
$EMXX $OPT -fwasm-exceptions -sWASM_LEGACY_EXCEPTIONS=1 -sUSE_FREETYPE=1 -sUSE_ZLIB=1 -o "$DIST/dvisvgm.mjs" "${OBJS[@]}" "$TEXOUT"/obj/kpathsea-*.o \
  -sMODULARIZE=1 -sEXPORT_ES6=1 -sEXPORT_NAME=createDvisvgm \
  -sENVIRONMENT=web,worker,node \
  -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=67108864 -sMAXIMUM_MEMORY=2147483648 \
  -sSTACK_SIZE=4194304 \
  -sFILESYSTEM=1 -sFORCE_FILESYSTEM=1 \
  -sINVOKE_RUN=0 -sEXIT_RUNTIME=1 \
  -sEXPORTED_FUNCTIONS=_main,_malloc,_free \
  -sEXPORTED_RUNTIME_METHODS=FS,callMain,ENV,NODEFS,MEMFS,stringToNewUTF8,UTF8ToString,HEAPU8 \
  -sINCOMING_MODULE_JS_API=arguments,thisProgram,preRun,postRun,print,printErr,locateFile,wasmBinary,noInitialRun,onRuntimeInitialized,instantiateWasm,onExit,quit \
  -sERROR_ON_UNDEFINED_SYMBOLS=1 \
  -lnodefs.js \
  -Wno-unused-command-line-argument
ls -l "$DIST/dvisvgm.mjs" "$DIST/dvisvgm.wasm"
