#!/usr/bin/env bash
# stage-site.sh DIR — assemble the deployable web tree into DIR: the demo pages
# and the guide under site/, the built library under dist/ (the layout of the
# release archive, so the pages' ../dist/ links work unchanged), a landing
# index.html, an .htaccess with the MIME types Apache needs for .wasm and .mjs,
# and the licence files. DIR is synced with --delete, but a Makefile, an
# `exclude` file and .DS_Store there are left alone.
#
#   scripts/stage-site.sh ~/Sites/jmckalex/software/mp-tikz-wasm   # then `make sync` there
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIR="${1:?usage: stage-site.sh DIR}"
for f in dist/mplib.wasm dist/tex.wasm dist/dvisvgm.wasm dist/luatex.wasm dist/index.js dist/auto.js dist/bundles/index.json site/guide.html site/standalone.html site/live.html site/minimal.html; do
  [ -f "$REPO/$f" ] || { echo "error: $f missing; run npm run build, build:guide, build:pages and build:standalone first" >&2; exit 1; }
done
STAGE="$(mktemp -d)"; trap 'rm -rf "$STAGE"' EXIT
mkdir -p "$STAGE/site"
cp -R "$REPO/dist" "$STAGE/dist"
rm -f "$STAGE"/dist/*.map "$STAGE"/dist/*/*.map
for f in index.html app.js examples.js examples-tikz.js tags.html guide.html minimal.html minimal-sources.js live.html live-sources.js page-common.js standalone.html; do
  cp "$REPO/site/$f" "$STAGE/site/$f"
done
cp -R "$REPO/site/examples" "$STAGE/site/examples"
cp -R "$REPO/site/figures" "$STAGE/site/figures"     # the tags page's saved figures (mpost-wasm --prerender)
cp "$REPO/README.md" "$REPO/NOTICE.md" "$REPO/LICENSE" "$STAGE/"
cp -R "$REPO/licenses" "$STAGE/licenses"
VERSION="$(node -p "require('$REPO/package.json').version")"
cat > "$STAGE/.htaccess" <<'HT'
# MIME types Apache does not know by default. Browsers refuse a type="module"
# script that is not served as JavaScript, and WebAssembly.instantiateStreaming
# needs application/wasm.
AddType text/javascript .js
AddType text/javascript .mjs
AddType application/wasm .wasm
AddType application/json .json
AddType text/plain .mp .tex .sty .cls .def .clo .cfg .fd .ltx .ini .enc .map .lua .dat .cnf
# The engines, the JavaScript and the TeX macro files compress three to five
# times; the bundles are fetched one file at a time.
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE application/wasm text/javascript application/json text/plain text/html text/css image/svg+xml
</IfModule>
# Without explicit freshness the browser revalidates every file on a return
# visit, one round trip each; a first TikZ run touches ninety. The bundle
# files are content-addressed by their manifest and change only with a
# release; the engines and the JavaScript change together on a rebuild.
<IfModule mod_expires.c>
  ExpiresActive On
  <If "%{REQUEST_URI} =~ m#/dist/bundles/#">
    ExpiresDefault "access plus 30 days"
  </If>
  <If "%{REQUEST_URI} =~ m#/dist/[^/]+\.(wasm|js|mjs|json)$#">
    ExpiresDefault "access plus 1 day"
  </If>
</IfModule>
HT
cat > "$STAGE/index.html" <<HTML
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>mp-tikz-wasm</title>
<style>
  body { margin: 0; padding: 40px 20px 60px; font: 17px/1.5 Georgia, "Times New Roman", serif; color: #18212b; background: #f7f8fa; }
  main { max-width: 640px; margin: 0 auto; }
  h1 { font: 700 34px/1.1 Georgia, serif; margin: 0 0 6px; }
  .sub { color: #5d6b7a; margin: 0 0 28px; }
  ul { list-style: none; padding: 0; margin: 0; }
  li { padding: 10px 0; border-top: 1px solid #d5dbe2; }
  li:last-child { border-bottom: 1px solid #d5dbe2; }
  a { color: #1f4e9c; text-decoration: none; font-weight: 700; } a:hover { text-decoration: underline; }
  li span { display: block; color: #5d6b7a; font-size: 15px; }
  p.foot { margin-top: 28px; color: #5d6b7a; font-size: 15px; }
  code { font: 14px Menlo, Consolas, monospace; }
</style>
</head>
<body>
<main>
<h1>mp-tikz-wasm</h1>
<p class="sub">MetaPost and TikZ in the browser, with real LaTeX. Version $VERSION. Everything on these pages is rendered by MetaPost, pdfTeX, LuaTeX and dvisvgm compiled to WebAssembly; nothing runs on the server.</p>
<ul>
  <li><a href="site/guide.html">Feature guide</a><span>The complete documentation, with every feature rendered by the engines themselves: installation, the drop-in tags, the API, the command line, how it works, fidelity, limits.</span></li>
  <li><a href="site/index.html">Editor demo</a><span>Galleries of MetaPost and TikZ examples with a live editor.</span></li>
  <li><a href="site/tags.html">Drop-in tags</a><span>A page whose diagrams are just <code>&lt;script type="text/tikz"&gt;</code> elements.</span></li>
  <li><a href="site/live.html">Real-time graphics</a><span>Six animations and interactive plots regenerated by MetaPost and LaTeX as you move the controls.</span></li>
  <li><a href="site/minimal.html">Two editors</a><span>A MetaPost editor and a TikZ editor side by side with their output.</span></li>
  <li><a href="site/standalone.html">Single-file playground</a><span>The same in one 11 MB file with everything inlined, for saving and using offline.</span></li>
</ul>
<p class="foot">Source, releases and the written documentation: <a href="https://github.com/jmckalex/mp-tikz-wasm">github.com/jmckalex/mp-tikz-wasm</a>. Licences: <a href="NOTICE.md">NOTICE.md</a>, <a href="LICENSE">LGPL-3.0</a>, <a href="licenses/GPL-3.0.txt">GPL-3.0</a>.</p>
</main>
</body>
</html>
HTML
mkdir -p "$DIR"
rsync -a --delete --exclude Makefile --exclude exclude --exclude .DS_Store "$STAGE/" "$DIR/"
echo "==> staged $(du -sh "$DIR" | cut -f1) in $DIR ($(find "$DIR" -type f | wc -l | tr -d ' ') files)"
